/**
 * Build script: reads RawCSV/*.csv and generates JS modules for next-word prediction.
 * Output: ../Corpus/bigrams.js, trigrams.js, 4grams.js, 5grams.js (used by the web app).
 * Each exports a map: prefix -> [{ word, freq }, ...] sorted by freq descending.
 *
 * Run from project root: node src/Features/Chat/Algorithm/RawCSV/build-ngrams.js
 * Or from this directory: node build-ngrams.js
 */

const fs = require('fs');
const path = require('path');

const RAWCSV_DIR = __dirname;
const CORPUS_DIR = path.join(__dirname, '..', 'Corpus');

if (!fs.existsSync(CORPUS_DIR)) {
  fs.mkdirSync(CORPUS_DIR, { recursive: true });
}

const FILES = [
  { csv: '2grams_english.csv', out: 'bigrams.js', varName: 'bigrams', n: 2 },
  { csv: '3grams_english.csv', out: 'trigrams.js', varName: 'trigrams', n: 3 },
  { csv: '4grams_english.csv', out: '4grams.js', varName: 'fourgrams', n: 4 },
  { csv: '5grams_english.csv', out: '5grams.js', varName: 'fivegrams', n: 5 },
];

function parseCsvLine(line) {
  const idx = line.indexOf(',');
  if (idx === -1) return null;
  const ngram = line.slice(0, idx).trim();
  const freqStr = line.slice(idx + 1).trim();
  const freq = parseInt(freqStr, 10);
  if (isNaN(freq)) return null;
  return { ngram, freq };
}

function buildIndex(csvPath, n) {
  const text = fs.readFileSync(csvPath, 'utf8');
  const lines = text.split(/\r?\n/).filter((l) => l.trim());
  const index = {};
  for (let i = 1; i < lines.length; i++) {
    const parsed = parseCsvLine(lines[i]);
    if (!parsed) continue;
    const parts = parsed.ngram.split(/\s+/);
    if (parts.length !== n) continue;
    const prefix = parts.slice(0, n - 1).join(' ').toLowerCase();
    const nextWord = parts[n - 1];
    if (!index[prefix]) index[prefix] = [];
    index[prefix].push({ word: nextWord, freq: parsed.freq });
  }
  for (const key of Object.keys(index)) {
    index[key].sort((a, b) => b.freq - a.freq);
  }
  return index;
}

function toJsModule(varName, index) {
  const content = JSON.stringify(index, null, 0);
  return `/** Generated by build-ngrams.js - do not edit by hand */\nexport const ${varName} = ${content};\n`;
}

for (const { csv, out, varName, n } of FILES) {
  const csvPath = path.join(RAWCSV_DIR, csv);
  const outPath = path.join(CORPUS_DIR, out);
  const exportName = varName || out.replace('.js', '');
  if (!fs.existsSync(csvPath)) {
    console.warn('Skip (missing):', csvPath);
    continue;
  }
  const index = buildIndex(csvPath, n);
  const js = toJsModule(exportName, index);
  fs.writeFileSync(outPath, js, 'utf8');
  console.log('Wrote', outPath, Object.keys(index).length, 'prefixes');
}
